### ISSUE TITLE
Error installation : need carbon

### ISSUE THREAD

**Issue by ldopi3** [OleVik/grav-plugin-timeline#14]
I have install timeline into my grav cms.

Centos 8 / Nginx / Php 74

I have this error : 
HP Fatal error:  Uncaught Error: Class 'Carbon\Language' not found in /var/www/html/grav-admin/user/plugins/timeline/timeline.php:135

![timeline](https://user-images.githubusercontent.com/79835857/116773199-60075480-aa54-11eb-91fd-e2787516c3ba.JPG)

**Comment by OleVik** [comment]
This seems to have been a problem with Grav 1.7 and Admin 1.10, where autoloading failed. It should be fixed in [v2.1.0](https://github.com/OleVik/grav-plugin-timeline/releases/tag/v2.1.0).

**Comment by inoas** [comment]
I have just installed 2.1.1 and the problem persists.

Installing this plugin as of now can take the whole system down. A simple fix is just deleting the plugin from the /user/plugins directory manually

```
$ bin/gpm uninstall timeline

Fatal error: Uncaught Error: Class 'Carbon\Language' not found in /web/development/grav/grav/user/plugins/timeline/timeline.php:132
Stack trace:
#0 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(445): Grav\Plugin\TimelinePlugin::getLanguageCodes()
#1 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(178): Grav\Common\Data\Blueprint->dynamicData(Array, 'options', Array)
#2 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(111): Grav\Common\Data\Blueprint->init()
#3 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(50): Grav\Common\Data\Blueprints->loadFile('timeline/bluepr...')
#4 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(260): Grav\Common\Data\Blueprints->get('timeline/bluepr...')
#5 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(231): Grav\Common\Plugins::get('timeline')
#6 /web/de in /web/development/grav/grav/user/plugins/timeline/timeline.php on line 132
```

**Comment by OleVik** [comment]
Can you confirm that the [/user/plugins/timeline/vendor/nesbot/carbon/src/Carbon/Language.php](https://github.com/OleVik/grav-plugin-timeline/blob/master/vendor/nesbot/carbon/src/Carbon/Language.php)-file exist?

**Comment by inoas** [comment]
Yes:

```
$ bin/gpm version
You are running Grav v1.7.15 [upgradable: v1.7.16]
```

```
$ bin/gpm install timeline

GPM Releases Configuration: Stable

Preparing to install Timeline [v2.1.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Clearing cache
...
```

```
$ bin/gpm uninstall timeline

Fatal error: Uncaught Error: Class 'Carbon\Language' not found in /web/development/grav/grav/user/plugins/timeline/timeline.php:132
Stack trace:
#0 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(445): Grav\Plugin\TimelinePlugin::getLanguageCodes()
#1 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(178): Grav\Common\Data\Blueprint->dynamicData(Array, 'options', Array)
#2 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(111): Grav\Common\Data\Blueprint->init()
#3 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(50): Grav\Common\Data\Blueprints->loadFile('timeline/bluepr...')
#4 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(260): Grav\Common\Data\Blueprints->get('timeline/bluepr...')
#5 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(231): Grav\Common\Plugins::get('timeline')
#6 /web/de in /web/development/grav/grav/user/plugins/timeline/timeline.php on line 132
```

```
$ ls -lha user/plugins/timeline/vendor/nesbot/carbon/src/Carbon/

total 800K
drwxr-x--- 10 u557974 nobody 4.0K Jun  5 17:27 ./
drwxr-x---  3 u557974 nobody 4.0K Jun  5 17:27 ../
-rw-r-----  1 u557974 nobody  416 Jun  5 17:27 CarbonConverterInterface.php
-rw-r-----  1 u557974 nobody  97K Jun  5 17:27 CarbonImmutable.php
-rw-r-----  1 u557974 nobody 236K Jun  5 17:27 CarbonInterface.php
-rw-r-----  1 u557974 nobody  89K Jun  5 17:27 CarbonInterval.php
-rw-r-----  1 u557974 nobody  74K Jun  5 17:27 CarbonPeriod.php
-rw-r-----  1 u557974 nobody  93K Jun  5 17:27 Carbon.php
-rw-r-----  1 u557974 nobody 8.2K Jun  5 17:27 CarbonTimeZone.php
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 Cli/
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 Doctrine/
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 Exceptions/
-rw-r-----  1 u557974 nobody  52K Jun  5 17:27 FactoryImmutable.php
-rw-r-----  1 u557974 nobody  53K Jun  5 17:27 Factory.php
drwxr-x---  2 u557974 nobody  20K Jun  5 17:27 Lang/
-rw-r-----  1 u557974 nobody 7.1K Jun  5 17:27 Language.php
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 Laravel/
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 List/
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 PHPStan/
drwxr-x---  2 u557974 nobody 4.0K Jun  5 17:27 Traits/
-rw-r-----  1 u557974 nobody  11K Jun  5 17:27 Translator.php
```

```
$ php --version
PHP 7.3.23 (cli) (built: Oct  2 2020 14:41:47) ( NTS )
```

**Comment by inoas** [comment]
Yes:

```
$ bin/gpm version

You are running Grav v1.7.15 [upgradable: v1.7.16]
```

```
$ bin/gpm install timeline

GPM Releases Configuration: Stable

Preparing to install Timeline [v2.1.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Clearing cache
...
```

```
$ bin/gpm uninstall timeline

Fatal error: Uncaught Error: Class 'Carbon\Language' not found in /web/development/grav/grav/user/plugins/timeline/timeline.php:132
Stack trace:
#0 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(445): Grav\Plugin\TimelinePlugin::getLanguageCodes()
#1 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprint.php(178): Grav\Common\Data\Blueprint->dynamicData(Array, 'options', Array)
#2 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(111): Grav\Common\Data\Blueprint->init()
#3 /web/development/grav/grav/system/src/Grav/Common/Data/Blueprints.php(50): Grav\Common\Data\Blueprints->loadFile('timeline/bluepr...')
#4 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(260): Grav\Common\Data\Blueprints->get('timeline/bluepr...')
#5 /web/development/grav/grav/system/src/Grav/Common/Plugins.php(231): Grav\Common\Plugins::get('timeline')
#6 /web/de in /web/development/grav/grav/user/plugins/timeline/timeline.php on line 132
```

```
$ ls -lha user/plugins/timeline/vendor/nesbot/carbon/src/Carbon/

total 800K
drwxr-x--- 10 _USER_ nobody 4.0K Jun  5 17:27 ./
drwxr-x---  3 _USER_ nobody 4.0K Jun  5 17:27 ../
-rw-r-----  1 _USER_ nobody  416 Jun  5 17:27 CarbonConverterInterface.php
-rw-r-----  1 _USER_ nobody  97K Jun  5 17:27 CarbonImmutable.php
-rw-r-----  1 _USER_ nobody 236K Jun  5 17:27 CarbonInterface.php
-rw-r-----  1 _USER_ nobody  89K Jun  5 17:27 CarbonInterval.php
-rw-r-----  1 _USER_ nobody  74K Jun  5 17:27 CarbonPeriod.php
-rw-r-----  1 _USER_ nobody  93K Jun  5 17:27 Carbon.php
-rw-r-----  1 _USER_ nobody 8.2K Jun  5 17:27 CarbonTimeZone.php
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 Cli/
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 Doctrine/
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 Exceptions/
-rw-r-----  1 _USER_ nobody  52K Jun  5 17:27 FactoryImmutable.php
-rw-r-----  1 _USER_ nobody  53K Jun  5 17:27 Factory.php
drwxr-x---  2 _USER_ nobody  20K Jun  5 17:27 Lang/
-rw-r-----  1 _USER_ nobody 7.1K Jun  5 17:27 Language.php
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 Laravel/
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 List/
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 PHPStan/
drwxr-x---  2 _USER_ nobody 4.0K Jun  5 17:27 Traits/
-rw-r-----  1 _USER_ nobody  11K Jun  5 17:27 Translator.php
```

```
$ php --version

PHP 7.3.23 (cli) (built: Oct  2 2020 14:41:47) ( NTS )
```

```
$ composer --version

Composer version 2.0.14 2021-05-21 17:03:37
```

**Comment by inoas** [comment]
Previous to attemping to install timeline

```
$ bin/gpm index --installed-only

GPM Releases Configuration: Stable

PLUGINS [ 64 ]

Packages table
--------------

+-------+--------------------------+--------------------------+----------------------+-----------+----------+
| Count | Name                     | Slug                     | Version              | Installed | Enabled  |
+-------+--------------------------+--------------------------+----------------------+-----------+----------+
| 1     | File Content             | file-content             | v1.0.0               | installed | enabled  |
| 2     | Markdown Color           | markdown-color           | v1.0.1               | installed | enabled  |
| 3     | Optimus                  | optimus                  | v1.3.0               | installed | disabled |
| 4     | Twig Cache               | twigcache                | v1.3.0               | installed | enabled  |
| 5     | Shortcode Assets         | shortcode-assets         | v1.0.2               | installed | enabled  |
| 6     | LightSlider              | lightslider              | v1.5.3               | installed | enabled  |
| 7     | Auto Date                | auto-date                | v1.0.2               | installed | enabled  |
| 8     | Featherlight             | featherlight             | v1.5.0               | installed | enabled  |
| 9     | Simple Responsive Ta...  | simple-responsive-tables | v1.1.1               | installed | enabled  |
| 10    | Maintenance              | maintenance              | v1.3.2               | installed | disabled |
| 11    | Admin Media Replace      | admin-media-replace      | v1.0.4               | installed | enabled  |
| 12    | Admin Media Actions      | admin-media-actions      | v1.0.4               | installed | enabled  |
| 13    | Custom JS                | custom-js                | v0.1.0               | installed | enabled  |
| 14    | Custom CSS               | custom-css               | v0.2.2               | installed | enabled  |
| 15    | Assets                   | assets                   | v2.0.1               | installed | enabled  |
| 16    | Admin Addon Media Re...  | admin-addon-media-rename | v1.6.3               | installed | enabled  |
| 17    | Pagination               | pagination               | v1.4.2               | installed | enabled  |
| 18    | Icalendar                | icalendar                | v0.2.3               | installed | enabled  |
| 19    | Lazysizes                | lazysizes                | v1.0.0               | installed | enabled  |
| 20    | TinyPNG                  | tinypng                  | v1.0.0               | installed | enabled  |
| 21    | Editable With Simple...  | editable-simplemde       | v1.1.2               | installed | enabled  |
| 22    | Swiper                   | swiper                   | v1.0.0               | installed | enabled  |
| 23    | Database                 | database                 | v1.0.2               | installed | disabled |
| 24    | PreCache                 | precache                 | v1.2.0               | installed | enabled  |
| 25    | Reading Time             | readingtime              | v1.4.0               | installed | enabled  |
| 26    | VCard                    | vcard                    | v0.1.0               | installed | enabled  |
| 27    | AdvancedPageCache        | advanced-pagecache       | v3.0.2               | installed | disabled |
| 28    | Directory Listing        | directorylisting         | v2.4.0               | installed | enabled  |
| 29    | Color Tools              | color-tools              | v1.0.1               | installed | enabled  |
| 30    | Error                    | error                    | v1.7.1               | installed | enabled  |
| 31    | Shortcode UI             | shortcode-ui             | v3.0.0               | installed | enabled  |
| 32    | Image Captions           | image-captions           | v2.0.2               | installed | enabled  |
| 33    | Quick Tray Links         | quick-tray-links         | v1.0.1               | installed | enabled  |
| 34    | Markdown Notices         | markdown-notices         | v1.1.0               | installed | enabled  |
| 35    | Anchors                  | anchors                  | v1.5.4               | installed | disabled |
| 36    | Archives                 | archives                 | v2.0.2               | installed | enabled  |
| 37    | Breadcrumbs              | breadcrumbs              | v1.6.1               | installed | enabled  |
| 38    | Admin Power Tools        | admin-power-tools        | v0.1.17              | installed | enabled  |
| 39    | Core Service Manager     | core-service-manager     | v1.1.4               | installed | enabled  |
| 40    | YouTube                  | youtube                  | v3.1.0               | installed | enabled  |
| 41    | Related Pages            | relatedpages             | v1.2.3               | installed | enabled  |
| 42    | Sitemap                  | sitemap                  | v3.0.1               | installed | enabled  |
| 43    | Highlight                | highlight                | v1.5.0               | installed | enabled  |
| 44    | TNT Search               | tntsearch                | v3.3.1               | installed | enabled  |
| 45    | Shortcode Owl Carous...  | shortcode-owl-carousel   | v1.0.4               | installed | enabled  |
| 46    | LangSwitcher             | langswitcher             | v1.4.2               | installed | enabled  |
| 47    | Translate Date           | translate-date           | v0.2.2               | installed | enabled  |
| 48    | Bootstrapper             | bootstrapper             | v3.0.0               | installed | disabled |
| 49    | Email                    | email                    | v3.1.2               | installed | enabled  |
| 50    | Shortcode Media          | shortcode-media          | v1.0.0               | installed | enabled  |
| 51    | Problems                 | problems                 | v2.1.1               | installed | enabled  |
| 52    | Form                     | form                     | v5.0.2               | installed | enabled  |
| 53    | Shortcode Core           | shortcode-core           | v5.0.6               | installed | enabled  |
| 54    | Page Inject              | page-inject              | v1.4.5               | installed | enabled  |
| 55    | Aura                     | aura                     | v2.1.2               | installed | enabled  |
| 56    | DevTools                 | devtools                 | v1.5.2               | installed | enabled  |
| 57    | Login                    | login                    | v3.4.3               | installed | enabled  |
| 58    | FullCalendar             | fullcalendar             | v0.2.9               | installed | disabled |
| 59    | SimpleSearch             | simplesearch             | v2.2.2               | installed | enabled  |
| 60    | Prism Highlighter        | prism-highlight          | v2.0.1               | installed | enabled  |
| 61    | Page Toc                 | page-toc                 | v1.1.1 -> v1.1.2     | installed | enabled  |
| 62    | Admin Panel              | admin                    | v1.10.15 -> v1.10.16 | installed | enabled  |
| 63    | Flex Objects             | flex-objects             | v1.0.11 -> v1.0.13   | installed | enabled  |
| 64    | Git Sync                 | git-sync                 | v2.3.1 -> v2.3.2     | installed | disabled |
```

**Comment by OleVik** [comment]
After testing with @inoas, this should be resolved by [v2.1.2](https://github.com/OleVik/grav-plugin-timeline/releases/tag/v2.1.2).
